databases:
  - name: blog_camisetas
    databaseName: blog_camisetas
    user: blog_camisetas

services:
  - type: web
    name: blog_camisetas
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_camisetas
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false