databases:
  - name: blog_camisetas
    databaseName: blog_camisetas
    user: blog_camisetas

services:
  - type: web
    name: blog_camisetas
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://blog_camisetas:jXMlBNU3zT3OkcYpS7zQYuvSC0wA66n8@dpg-ckoqb60ujous73dt6ccg-a/blog_camisetas
        fromDatabase:
          name: blog_camisetas
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false